language: python
python:
- nightly

install: true

script:
- python3 --version
- printf \\e[31mred\\e[39m
- printf \\033[31mred\\033[39m
- printf \\x1b[31mred\\x1b[39m
- python -c "print('\x1b[31mred\x1b[39m')"
- python -c "print('\N{CSI}31mred\N{CSI}39m')"
- python -c "print('\x1b[31mred\x1b[39m'.encode('ascii', 'namereplace'))"
- python -c "print('\N{CSI}'.encode('ascii', 'namereplace'))"
- python -c "print('\N{CSI}'.encode('utf-8'))"
- python -c "print('\N{GREEK CAPITAL LETTER DELTA}')"
- printf \\x1b[7mreverse video\\x1b[27m
- python -c "print('\x1b[7mreverse video\x1b[27m')"
- python -c "print('\x1b[A')" # cursor up
- python -c "print('\x1b[B')" # cursor down
- python -c "print('\x1b[C')" # cursor forward
- python -c "print('\x1b[D')" # cursor backward
- python -c "print('\x1b[A')"
- python -c "print('\x1b[B')"
- python -c "print('...\nX\x1b[AY\x1b[BZ')"
