language: python
# python:
# - "3.6"

script:
- printf \\e[31mred\\e[39m
- printf \\033[31mred\\033[39m
- printf \\x1b[31mred\\x1b[39m
- python3 -c "print('\x1b[31mred\x1b[39m')"
- printf \\x1b[7mreverse video\\x1b[27m
- python3 -c "print('\x1b[7mreverse video\x1b[27m')"
- python3 -c "print('\x1b[A')"
- python3 -c "print('\x1b[B')"
- python3 -c "print('\x1b[C')"
- python3 -c "print('\x1b[D')"
- python3 -c "print('\x1b[A')"
- python3 -c "print('\x1b[B')"
