language: python
# python:
# - "3.6"

script:
# - printf \\033c
# - printf \\ec
# printf \\x1bc
- python3 -c "print('\x1b[31mred\x1b[39m')"
- python3 -c "print('\x1b[A')"
- python3 -c "print('\x1b[B')"
- python3 -c "print('\x1b[C')"
- python3 -c "print('\x1b[D')"
- python3 -c "print('\x1b[A')"
- python3 -c "print('\x1b[B')"
- python3 -c "print('\x1b[7mreverse video\x1b[27m')"
